### ISSUE TITLE
BASIC INSTALLATION

### ISSUE THREAD

**Issue by Siddhant-Misra** [HamadaFMahdi/vue-body-part-selector#1]
### BASIC INSTALL

When trying to do an install. 
![image](https://user-images.githubusercontent.com/10378799/211396342-0b497b22-eae0-458b-82eb-fd01b20ac494.png)

Running Vue version: "^3.2.21".
Node Version: 14.17.6
NPM version: 8.3.2

**Comment by HamadaFMahdi** [comment]
It's currently not compatible with Vue 3. I will try to make a Vue 3 version soon.
